### ISSUE TITLE
HiveClient 中getTable()  没有trim comment，导致taier执行数据同步异常，此处需要trim的很多

### ISSUE THREAD

**Issue by zekai-li** [DTStack/DatasourceX#1]
![Uploading 1652515321278_7E8BC3AA-F2C9-448e-A09D-95013B3722B3.png…]()

**Comment by zekai-li** [comment]
![lQLPDhtsPbbteTbNAr_NBU6w3aY2WkqOJosCggPu1kCdAA_1358_703](https://user-images.githubusercontent.com/58294989/168416977-9c8d5fb8-7d8e-4e47-b2fe-12ed2e3288c2.png)

**Comment by poxiao8** [comment]
fix in v4.3.2
